### ISSUE TITLE
iDragon Game Using HTML, CSS, JAVASCRIPT

### ISSUE THREAD

**Issue by sudarsan2k5** [WeBeginners-Community/GGExtensions#1]
## Description:- 
Creating an iDragon game using HTML, CSS, and JavaScript can be a fun and creative project.

## Technologies used:-
* HTML
* CSS
* JAVA SCRIPT

### The image for the final project:-
![The image for the final project](https://github.com/WeBeginners-Community/GGExtensions/assets/108286640/b7a4e470-00cc-478f-a614-1d37454b636a)

**Comment by sudarsan2k5** [comment]
Hi 👋 @Sulagna-Dutta-Roy I would like to work on this issue. Could you please assign it to me with the 'hacktoberfest' tag?

**Comment by Sulagna-Dutta-Roy** [comment]
This is a browser extensions repository.

**Comment by sudarsan2k5** [comment]
I apologize for any confusion caused. I mistakenly opened an issue for a web development project in a repository intended for browser extensions. To rectify this, I will close and delete the original issue and create a new one, I look forward to working on this REPO.
